// Maps each character name to its avatar image path(s). This mirrors the client's
// avatar gallery so the server issues the SAME character image for a given name
// (instead of random emoji). The image files live under client/public/avatars/
// and are self-contained SVGs (generated by _gen_avatars.mjs) or JPGs.

// Every character can have multiple image variants. AVATAR_SETS maps each
// character name to an array of image paths. randomAvatar picks one randomly so
// each new connection gets a different look (image changes on refresh).
const IMG = {
  "Iron Man": "/avatars/characters/iron-man-1.jpg",
  "Captain America": "/avatars/characters/captain-america-1.jpg",
  "Thor": "/avatars/characters/thor-1.jpg",
  "Doctor Strange": "/avatars/characters/doctor-strange-1.jpg",
  "Hulk": "/avatars/characters/hulk.jpg",
  "Black Widow": "/avatars/characters/black-widow.jpg",
  "Hawkeye": "/avatars/characters/hawkeye.jpg",
  "Ant-Man": "/avatars/characters/ant-man.jpg",
  "Captain Marvel": "/avatars/characters/captain-marvel.jpg",
  "Loki": "/avatars/characters/loki.jpg",
  "Deadpool": "/avatars/characters/deadpool.jpg",
  "Groot": "/avatars/characters/groot.jpg",
  "Batman": "/avatars/characters/batman.jpg",
  "Flash": "/avatars/characters/flash.jpg",
  "Aquaman": "/avatars/characters/aquaman.jpg",
  "Joker": "/avatars/characters/joker.jpg",
  "Superman": "/avatars/characters/superman.jpg",
  "Wolverine": "/avatars/characters/wolverine.jpg",
  "Harry Potter": "/avatars/characters/harry-potter.jpg",
  "Hermione Granger": "/avatars/characters/hermione-granger.jpg",
  "Albus Dumbledore": "/avatars/characters/albus-dumbledore.jpg",
  "Severus Snape": "/avatars/characters/severus-snape.jpg",
  "Draco Malfoy": "/avatars/characters/draco-malfoy.jpg",
  "Rubeus Hagrid": "/avatars/characters/rubeus-hagrid.jpg",
  "Dobby": "/avatars/characters/dobby.jpg",
  "Sorting Hat": "/avatars/characters/sorting-hat.jpg",
  "Professor": "/avatars/characters/professor.jpg",
  "Tokyo": "/avatars/characters/tokyo.jpg",
  "Berlin": "/avatars/characters/berlin.jpg",
  "Denver": "/avatars/characters/denver.jpg",
  "Helsinki": "/avatars/characters/helsinki.jpg",
  "Naruto Uzumaki": "/avatars/characters/naruto.jpg",
  "Sasuke Uchiha": "/avatars/characters/sasuke.jpg",
  "Monkey D. Luffy": "/avatars/characters/luffy.jpg",
  "Sanji": "/avatars/characters/sanji.jpg",
  "Levi Ackerman": "/avatars/characters/levi.jpg",
  "Eren Yeager": "/avatars/characters/eren.jpg",
  "Goku": "/avatars/characters/goku.jpg",
};

export const AVATAR_SETS = Object.fromEntries(
  [
    "Iron Man","Spider-Man","Captain America","Thor","Hulk","Black Widow",
    "Hawkeye","Doctor Strange","Black Panther","Scarlet Witch","Vision","Falcon",
    "Winter Soldier","War Machine","Ant-Man","Wasp","Captain Marvel","Star-Lord",
    "Loki","Deadpool","Groot","Batman","Flash","Aquaman","Joker","Superman","Wolverine",
    "Harry Potter","Ron Weasley","Hermione Granger","Albus Dumbledore","Severus Snape",
    "Draco Malfoy","Sirius Black","Ginny Weasley","Rubeus Hagrid","Dobby","Sorting Hat",
    "Professor","Tokyo","Berlin","Rio","Nairobi","Denver","Helsinki","Oslo","Lisbon",
    "Palermo","Bogotá","Stockholm",
    "Naruto Uzumaki","Sasuke Uchiha","Kakashi Hatake","Itachi Uchiha","Monkey D. Luffy",
    "Roronoa Zoro","Sanji","Levi Ackerman","Eren Yeager","Goku",
  ].map((name) => [name, IMG[name] ? [IMG[name]] : []])
);

// Legacy single-path map — first variant of each character, so any existing
// code that reads AVATARS[name] still works.
export const AVATARS = Object.fromEntries(
  Object.entries(AVATAR_SETS).map(([name, paths]) => [name, paths[0]])
);

// Returns a random image path for a given character name. Used by the server so
// each new connection gets a different variant (image changes on refresh).
export function randomAvatar(name) {
  const set = AVATAR_SETS[name];
  if (!set || set.length === 0) return AVATARS[name];
  return set[Math.floor(Math.random() * set.length)];
}
